# Generated by Django 5.1.4 on 2025-01-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="supplier",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
