# Generated by Django 5.1.4 on 2025-01-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usermanager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserManager",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
