# Generated by Django 5.1.4 on 2025-01-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sector",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Comercial", "Comercial"),
                    ("Financeiro", "Financeiro"),
                    ("Jurídico", "Jurídico"),
                    ("Técnico", "Técnico"),
                    ("Suporte", "Suporte"),
                ],
                default="Suporte",
                max_length=50,
                null=True,
            ),
        ),
    ]
