# Generated by Django 5.1.4 on 2025-01-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="mac",
        ),
        migrations.RemoveField(
            model_name="product",
            name="serial_number",
        ),
    ]
