# Generated by Django 5.1.4 on 2025-01-16 12:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_remove_product_mac_remove_product_serial_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Implementation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mac", models.CharField(blank=True, max_length=100, null=True)),
                ("client", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("building_area", models.CharField(max_length=200)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="implementations",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["client"],
            },
        ),
    ]
