# Generated by Django 5.1.4 on 2025-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("implementations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="implementation",
            name="billing_date",
            field=models.DateField(default="2025-12-31"),
        ),
        migrations.AddField(
            model_name="implementation",
            name="cnpj",
            field=models.CharField(default="unknow", max_length=20),
        ),
        migrations.AddField(
            model_name="implementation",
            name="license",
            field=models.CharField(default="unknow", max_length=50),
        ),
        migrations.AddField(
            model_name="implementation",
            name="license_expiration_date",
            field=models.DateField(default="2025-12-31"),
        ),
        migrations.AddField(
            model_name="implementation",
            name="management",
            field=models.CharField(
                choices=[("Cliente", "Cliente"), ("Think Digital", "Think Digital")],
                default="Think Digital",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="implementation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Não iniciado", "Não iniciado"),
                    ("Implementação", "Implementação"),
                    ("Validação cliente", "Validação cliente"),
                    ("Concluída", "Concluída"),
                    ("Bloqueada", "Bloqueada"),
                ],
                default="Não iniciado",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="implementation",
            name="unifi_access",
            field=models.CharField(
                blank=True, default="unknow", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="implementation",
            name="unifi_management_ip",
            field=models.CharField(
                blank=True, default="unknow", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="implementation",
            name="unifi_observations",
            field=models.CharField(
                blank=True, default="unknow", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="implementation",
            name="unifi_password",
            field=models.CharField(
                blank=True, default="unknow", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="implementation",
            name="unifi_site_unity",
            field=models.CharField(
                blank=True, default="unknow", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="implementation",
            name="unifi_url_controller",
            field=models.CharField(
                blank=True, default="unknow", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="implementation",
            name="unit",
            field=models.CharField(default="Sede", max_length=50),
        ),
    ]
