# Generated by Django 5.1.4 on 2025-01-16 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("implementations", "0003_implementation_solution"),
        ("suppliers", "0003_alter_supplier_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="implementation",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="implementations",
                to="suppliers.supplier",
            ),
        ),
    ]
