# Generated by Django 5.1.4 on 2025-01-16 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("implementations", "0004_alter_implementation_supplier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="implementation",
            name="account_manager",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="implementations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="billing_date",
            field=models.DateField(blank=True, default="2025-12-31", null=True),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="building_area",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="solution",
            field=models.CharField(
                blank=True,
                choices=[("Zoox Wi-fi", "Zoox Wi-fi"), ("Propz", "Propz")],
                default="Zoox Wi-Fi",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="implementation",
            name="unit",
            field=models.CharField(
                blank=True, default="Sede", max_length=50, null=True
            ),
        ),
    ]
