# Generated by Django 5.1.4 on 2025-01-14 13:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outflows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outflow",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
