# Generated by Django 5.1.4 on 2025-01-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outflows", "0003_rename_implementd_outflow_implemented"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outflow",
            name="implemented",
            field=models.BooleanField(default=False),
        ),
    ]
